DROP TABLE IF EXISTS users_favourites CASCADE;

CREATE TABLE users_favourites (
  id SERIAL PRIMARY KEY NOT NULL,
  users_id VARCHAR(255) UNIQUE NOT NULL,
  shelters_id VARCHAR(255) UNIQUE NOT NULl,
  pets_id VARCHAR(255) UNIQUE NOT NULl
);
